# Project Config
spring.application.name = quad-assignment-backend

# Server Properties
server.port = 8080

# Trivia API
trivia.api.base-url = https://opentdb.com
trivia.api.rate-limit = PT5S
trivia.feature.ttl = PT10M
trivia.feature.cache-limit = 10000
