# Project Config
spring.application.name=quad-assignment-backend

# Server Properties
server.port=8080

# External APIs
quote.api.base-url=http://localhost:8080/api

# Enabled
feature.quote.enabled = false