# Project Config
spring.application.name = quad-assignment-backend

# Server Properties
server.port = 8080

# Trivia API
trivia.api.base-url = https://opentdb.com
trivia.api.rate-limit = PT5S

# Example Quote API
feature.quote.enabled = false
quote.api.base-url = http://localhost:8080/api